---
title: "p8105_hw6_sl5685"
author: "Shumei Liu"
date: "2024-12-02"
output: github_document
---

```{r}
library(tidyverse)
library(modelr)
library(broom)
library(rnoaa)
```

## Problem 1

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

head(weather_df)
```

```{r}
# Fit linear regression model
lm_model = lm(tmax ~ tmin, data = weather_df)

summary(lm_model)
```

```{r}
n_boot = 5000
set.seed(123)
```

```{r}
# Run Bootstrap Procedure
bootstrap_results = replicate(n_boot, {
  boot_sample = weather_df %>% sample_frac(replace = TRUE)
  fit = lm(tmax ~ tmin, data = boot_sample)
  r_squared = glance(fit)$r.squared
  coefs = tidy(fit)$estimate
  log_beta0_beta1 = log(coefs[1] * coefs[2])
  c(r_squared, log_beta0_beta1)
})

bootstrap_df = as.data.frame(t(bootstrap_results))
colnames(bootstrap_df) = c("r_squared", "log_beta0_beta1")
```

```{r}
# Calculate the 95% confidence interval for R-squared
ci_r_squared = quantile(bootstrap_df$r_squared, probs = c(0.025, 0.975))

ci_r_squared

# Calculate the 95% confidence interval for log(beta0 * beta1)
ci_log_beta0_beta1 = quantile(bootstrap_df$log_beta0_beta1, probs = c(0.025, 0.975))

ci_log_beta0_beta1
```

## Problem 2

```{r}
homicides = read_csv("./data/homicide-data.csv")
```

## Problem 3

```{r}
birthweight = read_csv("./data/birthweight.csv")
```

